<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"收容管理管理",
			            "menuJump":"列表",
			            "tableName":"shourong"
			        }
			    ],
			    "menu":"收容管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"在库犬管理",
			            "menuJump":"列表",
			            "tableName":"zaikuquan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在库犬收藏管理",
			            "menuJump":"列表",
			            "tableName":"zaikuquanCollection"
			        }
					 ,
					{
						"buttons":[
							"查看",
							"同意",
							"拒绝",
							"删除"
						],
						"menu":"收养犬管理",
						"menuJump":"列表",
						"tableName":"zaikuquanOrder"
					}
					 ,
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"已领养犬管理",
						"menuJump":"列表",
						"tableName":"yilingyang"
					}
			    ],
			    "menu":"在库犬管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"领养回访管理",
                        "menuJump":"列表",
                        "tableName":"lingyanghuifang"
                    }
                ],
                "menu":"领养回访管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"养狗咨询管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"养狗咨询管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"收容管理管理",
			            "menuJump":"列表",
			            "tableName":"shourong"
			        }
			    ],
			    "menu":"收容管理管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"在库犬管理",
			            "menuJump":"列表",
			            "tableName":"zaikuquan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在库犬收藏管理",
			            "menuJump":"列表",
			            "tableName":"zaikuquanCollection"
			        }
					 ,
					{
						"buttons":[
							"查看"
						],
						"menu":"收养犬管理",
						"menuJump":"列表",
						"tableName":"zaikuquanOrder"
					}
					 ,
					{
						"buttons":[
							"查看"
						],
						"menu":"已领养犬管理",
						"menuJump":"列表",
						"tableName":"yilingyang"
					}
			    ],
			    "menu":"在库犬管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"领养回访管理",
	                    "menuJump":"列表",
	                    "tableName":"lingyanghuifang"
	                }
	            ],
	            "menu":"领养回访管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"养狗咨询管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"养狗咨询管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
